name: Deploy wp-content (DEV via SFTP, PROD via FTPS)

on:
  push:
    branches: [ "dev", "main" ]
  workflow_dispatch:

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Artefact optionnel pour téléchargement manuel
      - name: Pack wp-content
        run: |
          mkdir -p out
          zip -r out/wp-content.zip wp-content || echo "no wp-content"
      - uses: actions/upload-artifact@v4
        with:
          name: wp-content
          path: out/wp-content.zip

  # -------- DEV (branche dev → webdevserver.fr) --------
  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to DEV via SFTP
        uses: appleboy/sftp-action@v0.6.0
        with:
          host: ${{ secrets.DEV_FTP_SERVER }}          # ex: ssh.webxxx.gpaas.net (sans sftp://)
          username: ${{ secrets.DEV_FTP_USERNAME }}
          password: ${{ secrets.DEV_FTP_PASSWORD }}
          port: 22
          source: "wp-content/*"                        # envoie le contenu de wp-content
          target: ${{ secrets.DEV_SERVER_DIR }}         # ex: /lamp0/web/vhosts/webdevserver.fr/htdocs/wp-content/
          strip_components: 1                           # supprime le préfixe "wp-content/"
          overwrite: true
          # timeout: 300s
          # use_insecure_cipher: true

  # -------- PROD (branche main → site officiel) --------
  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to PROD via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server:   ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps                              # change en 'ftp' ou 'ftps-legacy' si besoin
          local-dir: wp-content/
          server-dir: ${{ secrets.SERVER_DIR }}       # ex: /www/wp-content/
          exclude: |
            **/.git*
            **/.DS_Store
            **/node_modules/**
            **/vendor/**
            **/*.map
