name: Deploy wp-content (DEV & PROD via FTP)

on:
  push:
    branches: [ "dev", "main" ]
  workflow_dispatch:

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Pack wp-content (artifact facultatif)
        run: |
          mkdir -p out
          zip -r out/wp-content.zip wp-content || echo "no wp-content"
      - uses: actions/upload-artifact@v4
        with:
          name: wp-content
          path: out/wp-content.zip

  # ---- DEV = SFTP (webdevserver.fr) ----
  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: SFTP Deploy to DEV
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.DEV_FTP_SERVER }}   # ex: ssh.webxxx.gpaas.net (sans sftp://)
          username: ${{ secrets.DEV_FTP_USERNAME }}
          password: ${{ secrets.DEV_FTP_PASSWORD }}
          port: 22
          local_path: 'wp-content/*'
          remote_path: ${{ secrets.DEV_SERVER_DIR }}   # ex: /htdocs/wp-content/
          sftp_only: true
          # delete_remote_files: false   # laisse à false par sécurité
          # exclude: '.git,.github,node_modules,vendor,*.map'

  # ---- PROD = FTPS/FTP selon ton hébergeur ----
  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: FTP Deploy to PROD
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server:   ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # Choisis 1 seul protocole selon ton hébergeur PROD :
          protocol: ftps        # ou 'ftp' / 'ftps-legacy'
          local-dir: wp-content/
          server-dir: ${{ secrets.SERVER_DIR }}   # ex: /www/wp-content/
          exclude: |
            **/.git*
            **/.DS_Store
            **/node_modules/**
            **/vendor/**
            **/*.map
