name: Deploy Theme
on:
  push:
    branches: [dev, prod]
    paths:
      - 'wp-content/themes/theme/**'
  workflow_dispatch:
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - run: echo "OK"

