name: Deploy Theme (PROD - SFTP)

on:
  push:
    branches: [prod]
    paths:
      - 'wp-content/themes/theme/**'
  workflow_dispatch:

concurrency:
  group: deploy-prod
  cancel-in-progress: false

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate required secrets
        run: |
          test -n "${{ secrets.PROD_SFTP_SERVER }}"   || (echo "❌ PROD_SFTP_SERVER is empty" && exit 1)
          test -n "${{ secrets.PROD_SFTP_USERNAME }}" || (echo "❌ PROD_SFTP_USERNAME is empty" && exit 1)
          test -n "${{ secrets.PROD_SFTP_PASSWORD }}" || (echo "❌ PROD_SFTP_PASSWORD is empty" && exit 1)
          test -n "${{ secrets.SERVER_DIR }}"         || (echo "❌ SERVER_DIR is empty" && exit 1)
          echo "✅ All required secrets are present."

      - name: Deploy to PROD (SFTP)
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server:      ${{ secrets.PROD_SFTP_SERVER }}
          username:    ${{ secrets.PROD_SFTP_USERNAME }}
          password:    ${{ secrets.PROD_SFTP_PASSWORD }}
          port:        22
          sftp_only:   true
          # Upload UNIQUEMENT le thème
          local_path:  'wp-content/themes/theme/*'
          # Doit pointer EXACTEMENT sur le dossier du thème côté serveur
          remote_path: ${{ secrets.SERVER_DIR }}
