name: Deploy wp-content (DEV & PROD)

on:
  push:
    branches: [ "dev", "prod" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Pack wp-content
        run: |
          mkdir -p out
          zip -r out/wp-content.zip wp-content || echo "no wp-content"
      - uses: actions/upload-artifact@v4
        with:
          name: wp-content
          path: out/wp-content.zip

  deploy-prod:
    if: github.ref == 'refs/heads/prod'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Déploiement PROD via SFTP (wlixcc)
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.PROD_SFTP_SERVER }}
          username: ${{ secrets.PROD_SFTP_USERNAME }}
          password: ${{ secrets.PROD_SFTP_PASSWORD }}
          port: 22
          local_path: 'wp-content/'
          remote_path: '/www/wp-content/'
          sftp_only: true

