name: Deploy wp-content (DEV & PROD via FTP)

on:
  push:
    branches: [ "dev", "main" ]   # dev => webdevserver.fr, main => prod
  workflow_dispatch:

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Crée un ZIP artefact utile si tu veux publier manuellement
      - name: Pack wp-content
        run: |
          mkdir -p out
          if [ -d "wp-content" ]; then
            zip -r out/wp-content.zip wp-content
          else
            echo "::warning::No wp-content directory."
            mkdir -p out && echo "empty" > out/empty.txt
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wp-content
          path: out/wp-content.zip

  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: FTP Deploy to DEV
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server:   ${{ secrets.DEV_FTP_SERVER }}
          username: ${{ secrets.DEV_FTP_USERNAME }}
          password: ${{ secrets.DEV_FTP_PASSWORD }}
          # protocol: 'ftps'   # ou 'ftp' / 'ftps' / 'sftp' si besoin
          local-dir: wp-content/
          server-dir: ${{ secrets.DEV_SERVER_DIR }}  # ex: /htdocs/wp-content/
          exclude: |
            **/.git*
            **/.DS_Store
            **/node_modules/**
            **/vendor/**
            **/*.map

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: FTP Deploy to PROD
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server:   ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # protocol: 'ftps'   # ou 'sftp' selon l’hébergeur
          local-dir: wp-content/
          server-dir: ${{ secrets.SERVER_DIR }}       # ex: /htdocs/wp-content/
          exclude: |
            **/.git*
            **/.DS_Store
            **/node_modules/**
            **/vendor/**
            **/*.map
