name: Deploy wp-content (DEV & PROD via FTP/SFTP)

on:
  push:
    branches: [ "dev", "main" ]
  workflow_dispatch:

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create ZIP (facultatif)
        run: |
          mkdir -p out
          zip -r out/wp-content.zip wp-content || echo "no wp-content"
      - uses: actions/upload-artifact@v4
        with:
          name: wp-content
          path: out/wp-content.zip

  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to DEV via SCP (SFTP)
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DEV_FTP_SERVER }}
          username: ${{ secrets.DEV_FTP_USERNAME }}
          password: ${{ secrets.DEV_FTP_PASSWORD }}
          port: 22
          source: "wp-content/*"
          target: ${{ secrets.DEV_SERVER_DIR }}/

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to PROD via FTP/FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server:   ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps                        # ou 'ftp' si ton hébergeur le demande
          local-dir: wp-content/
          server-dir: ${{ secrets.SERVER_DIR }}
          exclude: |
            **/.git*
            **/.DS_Store
            **/node_modules/**
            **/vendor/**
            **/*.map
