name: Deploy wp-content (DEV & PROD via SFTP)

on:
  push:
    branches: [ "dev", "prod" ]
  workflow_dispatch:

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Artefact utile au besoin (téléchargement manuel)
      - name: Pack wp-content
        run: |
          mkdir -p out
          zip -r out/wp-content.zip wp-content || echo "no wp-content"
      - uses: actions/upload-artifact@v4
        with:
          name: wp-content
          path: out/wp-content.zip

  # ---------- DEV ----------
  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Deploy DEV via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server:   ${{ secrets.DEV_SFTP_SERVER }}     # ex: ssh.webxxx.gpaas.net
          username: ${{ secrets.DEV_SFTP_USERNAME }}
          password: ${{ secrets.DEV_SFTP_PASSWORD }}
          port: 22
          sftp_only: true
          local_path:  './wp-content'                  # pas de * ni de / final
          remote_path: '/lamp0/web/vhosts/webdevserver.fr/htdocs/wp-content'  # chemin exact dev

  # ---------- PROD ----------
  deploy-prod:
    if: github.ref == 'refs/heads/prod'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Deploy PROD via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server:   ${{ secrets.PROD_SFTP_SERVER }}    # hôte SFTP prod (comme dans FileZilla)
          username: ${{ secrets.PROD_SFTP_USERNAME }}
          password: ${{ secrets.PROD_SFTP_PASSWORD }}
          port: 22
          sftp_only: true
          local_path:  './wp-content'                  # pas de * ni de / final
          remote_path: '/www/wp-content'               # chemin exact prod
