name: Deploy Theme (PROD - DIAG)

on:
  workflow_dispatch:  # tu le lances à la main

jobs:
  deploy-prod-diag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1) Ajoute un marqueur UNIQUE dans style.css (en mémoire du run, sans committer)
      - name: Add deploy marker to style.css
        run: |
          MARK="/* DEPLOY-MARKER: $GITHUB_SHA $(date -u +'%Y-%m-%dT%H:%M:%SZ') */"
          echo "$MARK" | tee -a wp-content/themes/theme/style.css
          echo "Added marker:"
          tail -n 2 wp-content/themes/theme/style.css

      # 2) Déploiement SFTP (mêmes secrets que d’habitude)
      - name: Deploy to PROD (SFTP)
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server:      ${{ secrets.PROD_SFTP_SERVER }}
          username:    ${{ secrets.PROD_SFTP_USERNAME }}
          password:    ${{ secrets.PROD_SFTP_PASSWORD }}
          port:        22
          sftp_only:   true
          local_path:  'wp-content/themes/theme/*'
          remote_path: ${{ secrets.SERVER_DIR }}

      # 3) Vérifie EN LIGNE que la prod sert bien le fichier déployé
      #    (on lit le style.css public et on cherche le marqueur)
      - name: Verify live style.css contains the marker
        run: |
          set -e
          URL="https://givingtuesday.fr/wp-content/themes/theme/style.css?t=$(date +%s)"
          echo "Fetching: $URL"
          curl -sS "$URL" | tail -n 5 | tee last_lines.txt
          if grep -q "DEPLOY-MARKER: $GITHUB_SHA" last_lines.txt; then
            echo "✅ LIVE OK: le style.css en prod contient le marqueur"
          else
            echo "❌ LIVE KO: le style.css servi ne contient pas le marqueur"
            echo "   → soit mauvais répertoire distant, soit cache serveur/CDN, soit thème actif différent."
            exit 1
          fi
