name: Deploy Theme (PRO)

on:
  push:
    branches: [prod]
    paths:
      - 'wp-content/themes/theme/**'
  workflow_dispatch:

concurrency:
  group: deploy-prod
  cancel-in-progress: false

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to PROD (FTPS)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.PRO_SFTP_SERVER }}
          username: ${{ secrets.PRO_SFTP_USERNAME }}
          password: ${{ secrets.PRO_SFTP_PASSWORD }}
          protocol: ftps
          port: 21
          local-dir: wp-content/themes/theme/
          server-dir: ${{ secrets.SERVER_DIR }}
          dangerous-clean-slate: false
          exclude: |
            **/.git*
            **/.DS_Store
            **/node_modules/**
            **/src/**
