name: Deploy Theme (PROD - SFTP)

on:
  push:
    branches: [prod]
    paths:
      - 'wp-content/themes/theme/**'
  workflow_dispatch:

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to PROD (SFTP)
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server:      ${{ secrets.PROD_SFTP_SERVER }}
          username:    ${{ secrets.PROD_SFTP_USERNAME }}
          password:    ${{ secrets.PROD_SFTP_PASSWORD }}
          port:        22
          sftp_only:   true
          # ⚠️ si ton thème ne s'appelle pas "theme", remplace-le ci‑dessous
          local_path:  'wp-content/themes/theme/*'
          # ⚠️ SECRET = chemin EXACT côté serveur jusqu'au dossier du thème, slash final inclus
          remote_path: ${{ secrets.SERVER_DIR }}
